apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
  containers:
  - name: webapp
    image: docker.io/library/webapp:latest # More specific name
    [cite_start]imagePullPolicy: IfNotPresent # Safer than "Never" 
    ports:
    - [cite_start]containerPort: 5000 
